-- =============================================
-- DEPRECATED: Dùng các file mới bên dưới
-- =============================================
-- 1. database/AutoWork_Schema.sql   — Schema 35 bảng (từ EF Migration)
-- 2. database/AutoWork_SeedData.sql — Dữ liệu gói, kênh, settings, AI prompts
-- 3. database/AutoWork_Complete.sql — Hướng dẫn setup đầy đủ
--
-- Khuyến nghị: dotnet ef database update
--              rồi chạy AutoWork.API để seed users + demo data
-- =============================================
